config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts do
    resources :comments, only: [:create]
  end
  root 'home#index'

  get 'about', to: 'pages#about'

  get 'projects', to: 'pages#projects'

  get 'newsletter', to: 'pages#newsletter'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'

  get '/search', to: 'posts#search', as: 'search'

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :thumbnail
    validates :name, presence: true
    validates :title, presence: true, length: {maximum:110, minimum:10}
    validates :text, presence: true, length: {minimum:20}

    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id]) 
        @comment = @post.comments.new(comment_params)
        if @comment.save
            redirect_to @post
        else
            redirect_to @post
        end
    end

    def set_comment
        @comment = Comment.find(params[:post])
    end

    def comment_params
        params.require(:comment).permit(:commenter, :body, :post)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_posts = Post.order(created_at: :desc).limit(5)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @page_name = "ABOUT"
    end

    def projects
        @page_name = "PROJECTS"
    end
    
    def newsletter
        @page_name = "NEWSLETTER"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build

    Rails.logger.debug "Comments count: #{@post.comments.count}"
    Rails.logger.debug "Comments: #{@post.comments.to_a}"
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    query = params[:query]
    if query.present?
      sanitized_query = ActiveRecord::Base.sanitize_sql_like(query)
      query_for_ts = sanitized_query.split.map { |word| "#{word}:*" }.join(' | ')
  
      @posts = Post.where(
        "to_tsvector('portuguese', name || ' ' || text) @@ to_tsquery('portuguese', ?)",
        query_for_ts
      ).order(
        Arel.sql("ts_rank(to_tsvector('portuguese', name || ' ' || text), to_tsquery('portuguese', '#{query_for_ts}')) DESC")
      )
    else
      @posts = []
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :title, :text, :thumbnail)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
        #@ permite a visualização em outras partes do código
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account"
        else 
            render :new, status: :unprocessable_entity
        end
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password)
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment]) do |form| %>
    <% if comment.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this post from being saved:</h2>
  
        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :commenter, style: "display: block" %>
      <%= form.text_field :commenter %>
    </div>
  
    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.text_field :body %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/home/index.html.erb
<%= render "shared/navbar" %>

<div class = "page-title text-center text-break">
    <hr>
    <h1>THE BLOG</h1>
    <hr>
</div>

<div>
    <%= render "posts/recent_posts" %>

</div>
<%= link_to "My Blog", posts_path %>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>   

  <body style="background-color: #090D1F;">
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/about.html.erb
<%= render "shared/navbar" %>

<div class= "page-title text-center text-break">
    <hr>
    <h1><%= @page_name %></h1>
    <hr>
</div>

<%= render "shared/footer" %>

app/views/pages/newsletter.html.erb
<%= render "shared/navbar" %>

<div class= "page-title text-center text-break">
    <hr>
    <h1><%= @page_name %></h1>
    <hr>
</div>

<%= render "shared/footer" %>

app/views/pages/projects.html.erb
<%= render "shared/navbar" %>

<div class= "page-title text-center text-break">
    <hr>
    <h1><%= @page_name %></h1>
    <hr>
</div>

<%= render "shared/footer" %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <%= form.label :thumbnail %>
  <%= form.file_field :thumbnail %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <% if post.thumbnail.attached? %>
    <%= image_tag post.thumbnail %>
  <% end %>

  <p>
    <strong>Name:</strong>
    <%= post.name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= post.text %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= post.created_at %>
  </p>

</div>

app/views/posts/_recent_posts.html.erb
<div class="container my-5">
  <h2 class="text-light mb-4">Recent blog posts</h2>
  <% if @recent_posts.present? %>
    <div class="row">
      <% @recent_posts.each_with_index do |post, index| %>
        <% card_class = index == 0 ? "col-md-12" : "col-md-6" %>
        <div class="<%= card_class %> mb-4" >
          <%= link_to post_path(post), class: "text-decoration-none" do %>
            <div class="card bg-dark text-light border-0">
            <% if post.thumbnail.attached? %>
                <%= image_tag url_for(post.thumbnail), class: "card-img-top", alt: post.title %>
            <% else %>
                <%= image_tag "placeholder.jpg", class: "card-img-top", alt: "Imagem padrão" %>
            <% end %>
                <div class="card-body">
                <p class="text-primary"><%= post.created_at.strftime("%A, %d %b %Y") %></p>
                <h5 class="card-title"><%= post.title %></h5>
                <p class="card-text"><%= truncate(post.text, length: 100) %></p>
                </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>Nenhum post recente encontrado.</p>
  <% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/search.html.erb
<%= render "shared/navbar" %>

<div class = "page-title text-center text-break">
    <hr>
    <h1>THE BLOG</h1>
    <hr>
</div>

<h1>Showing all the results for "<%= params[:query] %>"</h1>
<% if @posts.present? %>
  <ul>
    <% @posts.each do |post| %>
      <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No results found for "<%= params[:query] %>". Try to search somenthing different.</p>
<% end %>

<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/navbar" %>
<hr>

<p style="color: green"><%= notice %></p>

<%= render @post %>


<div>
<%= link_to "Edit this post", edit_post_path(@post) %> |
<%= link_to "Back to posts", posts_path %>

<%= button_to "Destroy this post", @post, method: :delete %>
</div>

<hr>
  <h2>Comments</h2>

  <% if @post.comments.exists? %>
    <ul>
      <% @post.comments.each do |comment| %>
        <%= comment.commenter %> 
        <%= comment.body %> 
        <%= comment.created_at %>
      <% end %>
    </ul>
  <% else %>
    <p>Be the first to comment!</p>
  <% end %>
<hr>

  <h3>Add Comments</h3>

  <%= render "comments/form", comment: @comment%>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="text-center p-4" style="color:white;">
        © 2024 Bianka Costa | UI by 
        <a class="text-reset fw-bold" href="https://www.figma.com/community/file/1235152009438565697">Faqih Sopyan</a>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-custom navbar-expand-lg border-body px-5" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand fs-4" href="/"><b>The Blog</b></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-4">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <%= link_to "Projects", projects_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "About", about_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Newsletter", newsletter_path, class: "nav-link" %>
                </li>
            </ul>
            <form action="<%= search_path %>" method="get" class="d-flex">
                <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        </div>
    </div>
</nav>